version: '3' # 指定本 yml 依从的 compose 哪个版本制定的。
services:
  # 后端服务配置
  web:
    image: node:12-alpine # node镜像名称
    working_dir: /code # 工作目录，将工作目录设置为 /code。
    volumes: # 挂载点，由于容器删除了数据也会删除，我们把容器里的目录挂载到本地目录，容器挂载了的目录有任何改变，都会保存到本地，将主机的数据卷或着文件挂载到容器里。
      - .:/code # 把本地当前目录挂载到容器的/code目录
    ports: # 端口映射
      - '3000:3000' # 本地端口：容器端口
    command: npm start # 这条命令会在工作目录下执行，覆盖容器启动的默认命令。
  # mysql的配置
  mysql:
    image: mysql:5.6
    # 指定数据卷
    volumes:
      - ./data:/var/lib/mysql # 挂载当前的data目录到容器默认mysql存储目录
    environment: # 环境变量，如下指定数据的名字和链接密码
      - MYSQL_ROOT_PASSWORD=123456 # mysql的root密码
      - MYSQL_DATABASE=koa_docker # mysql的初始化数据库
    ports:
      - '3306:3306'
  # nginx 配置添加
  nginx:
    image: nginx:1.17
    volumes:
      - ./static:/code/static
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf # 挂在nginx服务的配置文件到容器里
    ports:
      - '80:80'
